### ISSUE TITLE
Default Emmet Behavior is broken

### ISSUE THREAD

**Issue by nicokoenig** [markuseckstein/vscode-kraut-ipsum-filler#1]
Hey Markus,

when I open a html file and enter `div` and press `tab`, nothing happens.

Seems like your extensions breaks the default emmet behavior for vs code :(

Would be great if you could fix that :)

Best regards,
Nico

**Comment by markuseckstein** [comment]
Thanks for informing me about that.
I'm afraid it is currently not possible to "bubble up" a key event which has been used to trigger an extension. 
I fixed it by now using the trigger "ctrl + tab" instead of only "tab" to trigger the extension.

br,
Markus
